name: Deploy NPM Package
on:
  push:
    branches:
      - main

jobs:

  core:
    name: Publish @supermatic-ui/core NPM package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies for core
        run: yarn install --frozen-lockfile
        working-directory: core

      - name: Install dependencies for vue-core
        run: yarn install --frozen-lockfile
        working-directory: vue-core

      - name: Install dependencies for react-core
        run: yarn install --frozen-lockfile
        working-directory: react-core

      - name: Install dependencies for vue-components
        run: yarn install --frozen-lockfile
        working-directory: vue-components

      - name: Install dependencies for react-components
        run: yarn install --frozen-lockfile
        working-directory: react-components

      - name: Build for core
        run: yarn build
        working-directory: core

      - name: Build for vue-core
        run: yarn build
        working-directory: vue-core

      - name: Build for react-core
        run: yarn build
        working-directory: react-core

      - name: Build for vue-components
        run: yarn build
        working-directory: vue-components
        
      - name: Build for react-components
        run: yarn build
        working-directory: react-components
        
      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=\${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish package for core
        run: npm publish --tolerate-republish
        working-directory: core

      - name: Publish package for vue-core
        run: npm publish --tolerate-republish
        working-directory: vue-core

      - name: Publish package for react-core
        run: npm publish --tolerate-republish
        working-directory: react-core

      - name: Publish package for vue-components
        run: npm publish --tolerate-republish
        working-directory: vue-components

      - name: Publish package for react-components
        run: npm publish --tolerate-republish
        working-directory: react-components