name: Deploy NPM Package
on:
  push:
    branches:
      - main

jobs:

  core:
    name: Publish @supermatic-ui/core NPM package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: core

      - name: Build
        run: yarn build
        working-directory: core
        
      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=\${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish package
        run: npm publish --tolerate-republish --access public
        working-directory: core

  # react-core:
  #   name: Publish @supermatic-ui/react-core NPM package
  #   uses: ./.github/workflows/npmjs_script.yaml
  #   with:
  #     dir: react-core
  #   secrets:
  #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  # react-components:
  #   name: Publish @supermatic-ui/react-components NPM package
  #   uses: ./.github/workflows/npmjs_script.yaml
  #   with:
  #     dir: react-components
  #   secrets:
  #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  # vue-core:
  #   name: Publish @supermatic-ui/vue-core NPM package
  #   uses: ./.github/workflows/npmjs_script.yaml
  #   with:
  #     dir: vue-core
  #   secrets:
  #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  # vue-components:
  #   name: Publish @supermatic-ui/vue-components NPM package
  #   uses: ./.github/workflows/npmjs_script.yaml
  #   with:
  #     dir: vue-components
  #   secrets:
  #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}